### ISSUE TITLE
Sink fails to load

### ISSUE THREAD

**Issue by secsubs** [thilinamb/flume-ng-kafka-sink#1]
My flume (1.5.0 on CDH) is:

a14.sources = r1
a14.channels = c1 
a14.sinks = k1 
a14.sources.r1.type = syslogtcp
a14.sources.r1.port = 5192
a14.sources.r1.host = localhost
a14.sources.r1.channels = c1 
a14.sources.r1.eventSize = 65536
a14.sources.r1.keepFields = true
a14.sources.r1.interceptors = i1 i2
a14.sources.r1.interceptors.i1.type = org.apache.flume.interceptor.TimestampInterceptor$Builder
a14.sources.r1.interceptors.i1.preserveExisting = true
a14.sources.r1.interceptors.i2.type = host
a14.sources.r1.interceptors.i2.useIP = false
a14.sources.r1.interceptors.i2.hostname.preserveExisting = true
a14.channels.c1.type = memory
a14.channels.c1.capacity = 400000
a14.channels.c1.transactionCapacity = 5000
a14.sinks.k1.type = com.thilinamb.flume.sink.KafkaSink
a14.sinks.k1.custom-topic = test-syslogstream-1
a14.sinks.k1.kafka.metadata.broker.list = kafka-broker-host:9092
a14.sinks.k1.kafka.serializer.class = kafka.serializer.StringEncoder
a14.sinks.k1.kafka.request.required.acks = 1
a14.sinks.k1.channel = c1

I have placed the sink jars in /var/lib/flume-ng/plugins.d: 
# ls -lt

total 10520
-rw-r--r-- 1 flume flume    6953 Aug  6 01:48 flume-kafka-sink-impl-0.5.0.jar
-rw-r--r-- 1 flume flume 3514920 Aug  6 01:48 kafka_2.10-0.8.1.1.jar
-rw-r--r-- 1 flume flume   82123 Aug  6 01:48 metrics-core-2.2.0.jar
-rw-r--r-- 1 flume flume 7137903 Aug  6 01:48 scala-library-2.10.1.jar

But when I run the agent, I get these errors:
2014-08-06 03:47:21,963 ERROR org.apache.flume.node.PollingPropertiesFileConfigurationProvider: Failed to load configuration data. Exception follows.
org.apache.flume.FlumeException: Unable to load sink type: com.thilinamb.flume.sink.KafkaSink, class: com.thilinamb.flume.sink.KafkaSink
    at org.apache.flume.sink.DefaultSinkFactory.getClass(DefaultSinkFactory.java:69)
    at org.apache.flume.sink.DefaultSinkFactory.create(DefaultSinkFactory.java:41)
    at org.apache.flume.node.AbstractConfigurationProvider.loadSinks(AbstractConfigurationProvider.java:415)
    at org.apache.flume.node.AbstractConfigurationProvider.getConfiguration(AbstractConfigurationProvider.java:103)
    at org.apache.flume.node.PollingPropertiesFileConfigurationProvider$FileWatcherRunnable.run(PollingPropertiesFileConfigurationProvider.java:140)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.thilinamb.flume.sink.KafkaSink
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:190)
    at org.apache.flume.sink.DefaultSinkFactory.getClass(DefaultSinkFactory.java:67)

**Comment by thilinamb** [comment]
If you are copying the jars in to the plugins.d directory, it should have a specific format.

More information can be found in Flume user guide. : [https://flume.apache.org/FlumeUserGuide.html#the-plugins-d-directory](https://flume.apache.org/FlumeUserGuide.html#the-plugins-d-directory)

You should create a directory inside the plugins.d directory for this custom sink. You can give it any name.
Inside that directory there should be two sub directories called  **lib** and **libext**. The **flume-kafka-sink-impl-0.5.0.jar should go into lib directory** while the **other 3 jars should go into libext** directory.

Let me know if this fixes your problem.

Cheers,
Thilina

**Comment by secsubs** [comment]
Thanks Thilina,

That worked. However, I think your sample config has an issue. For setting
topic, this works:
a14.sinks.k1.topic = test-syslogstream-1

Not,
a14.sinks.k1.custom-topic = thilina

I am using Kafka 0.8.1.1 and flume 1.5.

**Comment by thilinamb** [comment]
I'm glad that you got it working. Also thanks for pointing out the mistake in the example config. I'll fix that. Also I'll update the documentation about using the plugins directory.

**Comment by secsubs** [comment]
Thanks Thilina. I will be pushing my contacts to include the sink in flume
trunk. So far, it seems to be working well.

**Comment by thilinamb** [comment]
Thanks @secsubs, that would be great. I've updated the docs and sample configs.

**Comment by rambozzz** [comment]
Hi, may you help me out with my problem? It seems to be similar. This is the question I just edited 2 hours ago on Stackoverflow:
https://stackoverflow.com/questions/47138367/make-fiware-cygnus-storing-to-apache-phoenix-database
